### ISSUE TITLE
NoHeapDB issue with get and snapshot location

### ISSUE THREAD

**Issue by tuhuynh27** [tuhuynh27/keva#5]
- Get no exist key return offset 0 => Unexpected
- `snapshotLocation = ""` didn't work, must be set to `snapshotLocation = "./"`
- Write tests for NoHeapDB

**Comment by tuhuynh27** [comment]
@axblueblader Please update here if there are any other issues are discovered

**Comment by axblueblader** [comment]
For Get issue, the problem is with these 2 function:
https://github.com/tuhuynh27/keva/blob/8ed90dad979a5be72f0d6d3b540e11090cfaec4c/store/src/main/java/com/jinyframework/keva/store/IndexStoreImpl.java#L300
https://github.com/tuhuynh27/keva/blob/8ed90dad979a5be72f0d6d3b540e11090cfaec4c/store/src/main/java/com/jinyframework/keva/store/IndexStoreImpl.java#L320

The condition check offset == -1 to determine key is not found, but the hash function always returns an offset no matter what key is input
